### ISSUE TITLE
Voice names are overlapping in SVG

### ISSUE THREAD

**Issue by tasmo** [benjaffe/logseq-music-notation#3] opened 2023-11-23 21:07 UTC
When noting [Multiple Voices](https://abcnotation.com/wiki/abc:standard:v2.1#multiple_voices) the names on the left are overlapping with the notation system.

Here is an example:

```music-abc
X:3
T:Happy Birthday
T:for String Quartet
T:and Vocal
M:3/4
Q:1/4=90
L:1/4
K:C
V:1 name="Violin I/Vocal"
G/2>G/2| A G c| B2 |
w: Hap-py birth-day to you
V:2 name="Violin II"
E| F G2| G2|
V:3 name="Viola" clef=alto
C| B,2 E| D2|
V:4 name="Cello" clef=bass
C,| F, E,/2-D,/2 C,| G, G,,|
```

Result:

![ABC](https://github.com/benjaffe/logseq-music-notation/assets/102685/f64506c0-93d5-4509-a5c6-848faa36d2e9)

**Comment by phoebejaffe** [comment] 2024-10-07 03:43
Thanks @tasmo, and wow, sorry for the almost year-late reply! This looks like an issue with one of the libraries I built on top of... either `abcjs` or `@folkdb/abc-render-svg`. Marking as closed since it's not a bug with this plugin directly.

**Closed as completed by phoebejaffe** 2024-10-07 03:43 UTC
